"""
Export the current database back into seed_data.py format.

Solves the drift problem where shoes/retailers added through the UI never made
it back into seed_data.py and were lost on reset. Call this, save the returned
content over backend/seed_data.py, and a fresh `python seed_data.py` reproduces
your current tracked shoes and retailers.
"""
from fastapi import APIRouter, Depends
from fastapi.responses import PlainTextResponse
from sqlalchemy.orm import Session

from app.database import get_db
from app.models.models import Retailer, Shoe

router = APIRouter(prefix="/export", tags=["export"])


def _generate_seed_source(db: Session) -> str:
    """Render the current retailers + shoes as runnable seed_data.py source."""
    retailers = db.query(Retailer).order_by(Retailer.id).all()
    shoes = db.query(Shoe).order_by(Shoe.brand, Shoe.model).all()

    lines = [
        '"""',
        "Seed script to populate initial data for retailers and shoes",
        "Run this after the database is initialized.",
        "",
        "AUTO-GENERATED by GET /api/export/seed-data — overwrites the hand-written",
        "seed_data.py to keep it in sync with the database.",
        '"""',
        "from app.database import SessionLocal, init_db",
        "from app.models.models import Retailer, Shoe",
        "",
        "",
        "def seed_retailers():",
        '    """Add Canadian running shoe retailers"""',
        "    db = SessionLocal()",
        "",
        "    retailers = [",
    ]

    for r in retailers:
        lines.append("        {")
        lines.append(f"            {'name'!r}: {r.name!r},")
        lines.append(f"            {'base_url'!r}: {r.base_url!r},")
        lines.append(f"            {'is_active'!r}: {bool(r.is_active)!r},")
        lines.append(f"            {'scraping_enabled'!r}: {bool(r.scraping_enabled)!r},")
        lines.append(f"            {'scraper_config'!r}: {r.scraper_config!r},")
        lines.append("        },")

    lines += [
        "    ]",
        "",
        "    for retailer_data in retailers:",
        "        existing = db.query(Retailer).filter(Retailer.name == retailer_data['name']).first()",
        "        if not existing:",
        "            db.add(Retailer(**retailer_data))",
        "            print(f\"✅ Added retailer: {retailer_data['name']}\")",
        "        else:",
        "            print(f\"⏭️  Retailer already exists: {retailer_data['name']}\")",
        "",
        "    db.commit()",
        "    db.close()",
        "",
        "",
        "def seed_shoes():",
        '    """Add running shoes to track"""',
        "    db = SessionLocal()",
        "",
        "    shoes = [",
    ]

    for s in shoes:
        parts = [f"{'brand'!r}: {s.brand!r}", f"{'model'!r}: {s.model!r}",
                 f"{'target_price'!r}: {float(s.target_price)!r}"]
        if s.notes:
            parts.append(f"{'notes'!r}: {s.notes!r}")
        parts.append(f"{'is_active'!r}: {bool(s.is_active)!r}")
        lines.append("        {" + ", ".join(parts) + "},")

    lines += [
        "    ]",
        "",
        "    for shoe_data in shoes:",
        "        existing = db.query(Shoe).filter(",
        "            Shoe.brand == shoe_data['brand'],",
        "            Shoe.model == shoe_data['model'],",
        "        ).first()",
        "        if not existing:",
        "            db.add(Shoe(**shoe_data))",
        "            print(f\"✅ Added shoe: {shoe_data['brand']} {shoe_data['model']}\")",
        "        else:",
        "            print(f\"⏭️  Shoe already exists: {shoe_data['brand']} {shoe_data['model']}\")",
        "",
        "    db.commit()",
        "    db.close()",
        "",
        "",
        'if __name__ == "__main__":',
        '    print("🌱 Starting database seeding...")',
        "    init_db()",
        "    seed_retailers()",
        "    seed_shoes()",
        '    print("✅ Seeding complete!")',
        "",
    ]

    return "\n".join(lines)


@router.get("/seed-data", response_class=PlainTextResponse)
def export_seed_data(db: Session = Depends(get_db)):
    """
    Return current retailers + shoes rendered as seed_data.py source code.

    Served as text/plain so the frontend can offer it as a direct download.
    """
    return _generate_seed_source(db)
